### ISSUE TITLE
White background in tooltip button

### ISSUE THREAD

**Issue by tostrem** [caduandrade/japura-gui#2]
Hi,
Very nice library of gui components.

Using the ToolTipButton I get a white background in the tooltip text.

I can override it by using style attribute in the body tag of the html text. however there is still a white border around the text.
Clearing the border of the tooltipLabel in the private showToolTip() method helps to resolve the issue. However it is not accessible outside the class

![tooltipbackground](https://cloud.githubusercontent.com/assets/4808082/7649638/27494326-faef-11e4-8720-a60c92811b1f.png)

Using jdk1.8.0_45

Kind regards,
Trond Østrem

**Comment by caduandrade** [comment]
what

**Comment by caduandrade** [comment]
Hi Trond,

I can see that you not using the default look and feel. What are you using?

**Comment by tostrem** [comment]
Hi Eduardo,

Yes I am using Nimbus: com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel

br,
-Trond

--------- Original Message --------- Subject: Re: [japura-gui] White background in tooltip button (#2)

**Comment by caduandrade** [comment]
Now I got the problem (even with null border). Its is a Nimbus problem. I will see what I can do.

**Comment by caduandrade** [comment]
Nimbus ignores opaque false. But I found into Nimbus code:
Component c = ctx.getComponent();
        Color bg = (c != null) ? c.getBackground() : null;
        if (bg == null || bg.getAlpha() > 0){
            Painter backgroundPainter = style.getBackgroundPainter(ctx);
            if (backgroundPainter != null) {
                paint(backgroundPainter, ctx, g, x, y, w, h,transform);
            }
        }

so... I can use color with alpha 0.

**Comment by caduandrade** [comment]
mission accomplished.

version 7.4.1 released. Thanks!

**Comment by tostrem** [comment]
Yes, that makes sense as it seemed like the opaque didn't apply.

Ex on my local copy using setBackground(new Color(255,255,220,0)) (or any rgb values) on the tooltipLabel variable indise the showToolTip() method  I get the desired effect.

-Trond

--------- Original Message --------- Subject: Re: [japura-gui] White background in tooltip button (#2)
